---
- name: Ensure that we have a DB
  mysql_db:
    name={{ django_dbname }}
    encoding={{ mariadb_db_encoding|default('utf8mb4') }}

- name: Ensure that we have a DB user
  mysql_user:
    name: "{{ django_dbuser }}"
    priv: "{{ django_dbname }}.*:ALL,GRANT/test_{{ django_dbname }}.*:ALL,GRANT"
    password: "{{ django_dbpass }}"

- name: Is our databate empty?
  shell: "mysql -e \"select if(count(*)>0,'populated','empty') as status from information_schema.tables where TABLE_SCHEMA = '{{ django_dbname }}'\""
  register: mariadb_db_empty_check
  changed_when: "'empty' in mariadb_db_empty_check.stdout"

