---
- name: Ensure packages needed for mariadb are present
  apt: "name={{ item }} state=latest"
  with_items:
    - mariadb-server
    - mariadb-client
    - libmysqlclient-dev # for Python's mysqlclient pkg
    - python-mysqldb # for ansible's mysql module

- name: Ensure that mariadb is started
  service: name=mysql state=started enabled=yes

- name: Drop our DB (so that we can re-import it)
  mysql_db: name={{ django_dbname }} state=absent
  when: django_force_db_import

- name: Ensure that we have a DB
  mysql_db: "name={{ django_dbname }}"

- name: Ensure that we have a DB user
  mysql_user:
    name: "{{ django_dbuser }}"
    priv: "{{ django_dbname }}.*:ALL,GRANT/test_{{ django_dbname }}.*:ALL,GRANT"
    password: "{{ django_dbpass }}"
- include: mariadb_importdump.yml
  when: "{{ django_initial_archive_path != '' }}"
