- name: Create nginx sites config
  template: src=django.conf dest=/etc/nginx/sites-available/{{ django_name }}.conf
  notify:
    - nginx restart

- name: Create symbolic links for sites config to enable sites
  file:
    path: "/etc/nginx/sites-enabled/{{ django_name }}.conf"
    state: link
    src: "/etc/nginx/sites-available/{{ django_name }}.conf"
  notify:
    - nginx restart
