---
- name: apt-get update/upgrade
  apt: update_cache=yes upgrade=yes cache_valid_time=3600
- name: Ensure packages needed for basic provisioning are present
  apt: name={{ item }} state=latest
  with_items:
    - rsync
    - sudo
    - build-essential
- name: Ensure that django_user exists
  user:
    name: "{{ django_user }}"
    createhome: no
    shell: /bin/bash

